name: Build UpdateProjectInfo EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: py -m pip install --upgrade pip openpyxl pyinstaller

      - name: Build exe with PyInstaller
        run: py -m PyInstaller --onefile --noconsole UpdateProjectInfo.py

      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UpdateProjectInfo
          path: dist/UpdateProjectInfo.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/UpdateProjectInfo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
